### ISSUE TITLE
Custom view sometimes shows grey bordered.

### ISSUE THREAD

**Issue by Nautiyalsachin** [jdg/MBProgressHUD#555] opened 2018-12-11 14:24 UTC
Hey there, I just tried adding a custom view animation but I am getting a grey bordered at the bottom of the progress indicator. Can you please help me to remove it. 

Thanks.

**Comment by tomaszmaciejko** [comment] 2019-01-22 23:38
@Nautiyalsachin Can you provide steps to reproduce or example project so this issue could be tracked down?

**Comment by Nautiyalsachin** [comment] 2019-01-24 07:58
Here is the code I am using : - 

extension UIViewController {
    
    func showLottieHUD(_ text : String? = "Loading...") {
        DispatchQueue.main.async {
            let hud = MBProgressHUD.showAdded(to: self.view, animated: true)
            hud.isUserInteractionEnabled = false
            hud.contentColor =  UIColor(hex: "5891FF")
            if let text = text {
                hud.label.text = text
            }
        }
    }

And sometimes it shows - 

![img_5bf3a07cd71c-1](https://user-images.githubusercontent.com/14342956/51663115-ddbd9980-1fdb-11e9-9dfa-d555ba5751a6.jpeg)

**Comment by Nautiyalsachin** [comment] 2019-01-24 08:08
I tried hud.button.isHidden = true, not sure if its a persistent issue or not.

**Comment by matej** [comment] 2020-01-13 22:06
This looks like it's another report for https://github.com/jdg/MBProgressHUD/issues/587. The problem should be fixed now.

**Closed by matej** 2020-01-13 22:06 UTC
