### ISSUE TITLE
Getting a crash with updating bezel motion effects

### ISSUE THREAD

**Issue by jumpingfrog0** [jdg/MBProgressHUD#563] opened 2019-04-09 04:54 UTC
Our crash collection system got a crash issue from a user's device,I check the dump file, find it crash at `-[MBProgressHUD updateBezelMotionEffects]`.
Device: iPhone 6 Plus
System version: 10.3.2

But I can not repeat on another devices, I don't know what wrong with the device.
Who can help me find out this issue?

Here is a piece of information of dump file:
```
Operating system: iOS
                  10.3.2 14F89
CPU: arm64
     2 CPUs

Crash reason:  EXC_BAD_INSTRUCTION / EXC_ARM_UNDEFINED
Crash address: 0x100627234
Process uptime: 49 seconds

Thread 0 (crashed)
 0  BiLin!-[MBProgressHUD updateBezelMotionEffects] [MBProgressHUD.m : 503 + 0x0]
    Found by: given as instruction pointer in context
 1  BiLin!-[MBProgressHUD setupViews] [MBProgressHUD.m : 336 + 0xc]
    Found by: previous frame's frame pointer
 2  BiLin!-[MBProgressHUD commonInit] [MBProgressHUD.m : 113 + 0xc]
    Found by: previous frame's frame pointer
 3  BiLin!-[MBProgressHUD initWithFrame:] [MBProgressHUD.m : 120 + 0xc]
    Found by: previous frame's frame pointer
 4  BiLin!-[BLProgressHUD hud] + 0x4c
    Found by: previous frame's frame pointer
 5  BiLin!+[BLProgressHUD showImage:msg:duration:inView:] + 0x74
    Found by: previous frame's frame pointer
 6  BiLin!+[BLProgressHUD showProcessMsg:inView:] + 0x40
    Found by: previous frame's frame pointer
 7  BiLin!-[BLRoomAudienceTableViewController loadData] [BLRoomAudienceTableViewController.m : 55 + 0x10]
    Found by: previous frame's frame pointer
 8  BiLin!-[BLRoomAudienceTableViewController viewDidLoad] [BLRoomAudienceTableViewController.m : 38 + 0xc]
    Found by: previous frame's frame pointer
 9  UIKit!-[UIViewController loadViewIfRequired] + 0x408
    Found by: previous frame's frame pointer
10  UIKit!-[UIViewController __viewWillAppear:] + 0x80
    Found by: previous frame's frame pointer
11  UIKit!-[UINavigationController _startCustomTransition:] + 0x474
    Found by: previous frame's frame pointer
12  UIKit!-[UINavigationController _startDeferredTransitionIfNeeded:] + 0x2a0
    Found by: previous frame's frame pointer
13  UIKit!-[UINavigationController __viewWillLayoutSubviews] + 0x3c
    Found by: previous frame's frame pointer
14  UIKit!-[UILayoutContainerView layoutSubviews] + 0xb8
    Found by: previous frame's frame pointer
15  UIKit!-[UILayoutContainerViewAccessibility layoutSubviews] + 0x30
    Found by: previous frame's frame pointer
16  UIKit!-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 0x4ac
    Found by: previous frame's frame pointer
17  QuartzCore!-[CALayer layoutSublayers] + 0x90
    Found by: previous frame's frame pointer
18  QuartzCore!CA::Layer::layout_if_needed(CA::Transaction*) + 0x120
    Found by: previous frame's frame pointer
19  QuartzCore!CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 0x1c
    Found by: previous frame's frame pointer
20  QuartzCore!CA::Context::commit_transaction(CA::Transaction*) + 0xf8
    Found by: previous frame's frame pointer
21  QuartzCore!CA::Transaction::commit() + 0x1f4
    Found by: previous frame's frame pointer
22  QuartzCore!CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 0x74
    Found by: previous frame's frame pointer
23  CoreFoundation!__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 0x1c
    Found by: previous frame's frame pointer
24  CoreFoundation!__CFRunLoopDoObservers + 0x170
    Found by: previous frame's frame pointer
25  CoreFoundation!__CFRunLoopRun + 0x3b8
    Found by: previous frame's frame pointer
26  CoreFoundation!CFRunLoopRunSpecific + 0x1a4
    Found by: previous frame's frame pointer
27  GraphicsServices!GSEventRunModal + 0x60
    Found by: previous frame's frame pointer
28  UIKit!UIApplicationMain + 0xcc
    Found by: previous frame's frame pointer
29  BiLin!main [main.m : 17 + 0x10]
    Found by: previous frame's frame pointer
30  libdyld.dylib!start + 0x0
    Found by: previous frame's frame pointer
```

**Comment by XiangWen** [comment] 2019-07-05 02:42
i faced the same problem which caused by the mehtod : updateBezelMotionEffects

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState] PID: 4442, TID: 837820, Thread name: com.google.Maps.LabelingBehavior, Queue name: com.apple.root.default-qos.overcommit, QoS: 21

**Comment by matej** [comment] 2020-01-13 22:04
This looks like a duplicate of https://github.com/jdg/MBProgressHUD/issues/552. Hopefully this is now resolved.

**Closed by matej** 2020-01-13 22:04 UTC
